FROM ubuntu:14.04
MAINTAINER yang o3
RUN apt-get update && \
    apt-get install -y build-essential \
    libssl-dev \
    python \
    vim \
    openssh-server \
    git \
    curl \
    npm
RUN useradd -d /home/yang -ms /bin/bash -g root -G sudo -p 123456 yang












